### ISSUE TITLE
Changes in tables not always propagating into WMS/WFS

### ISSUE THREAD

**Issue by woutergd** [geoserver/geoserver-cloud#222]
We currently have deployed the geoserver cloud instance in a test environment with a shared data directory backend. We connected it to a postgres database to publish layers. This works all fine.

However, when we decide to update the attributes of a table, the WMS and WFS services are not providing the additional attributes (or stops working when we remove an attribute from the database)

Summarized, we tested the following:
 * Access the layer through layer preview, and access the feature info;
 * Add a new attribute in the database;
 * Through web interface and rest API, the attribute shows up when creating a new layer based on the same table (Web and Rest) or reloading attributes (Web only, not available in rest api);
 * When going back to the layer preview, the new column isn't shown, also not as empty field;
 * After restarting the WMS and WFS service, the new column is recognized and working correctly.

I expect that there is somewhere a cache, which keeps track of the attributes per table / store, as it doesn't matter if we recreate it with either the same or a different name, the issue occurs if the same table is used.

If any additional testing is helpful, or any clarification is wanted, just let me know.

**Comment by woutergd** [comment]
By the way I think it is related to the Resource cache / Feature Type cache size. I also checked our config, the feature type cache size is already put at 0 (so I expect no cache). In addition, clearing the cache with the 'Clear' button of the Resource cache on the status page in the UI makes no changes in the result, still the attributes aren't recognized.

**Comment by groldan** [comment]
Thanks for the report @woutergd, looks like a legit bug, related to #150
I'll take a look asap but can't promise it'll be fixed this week.

**Comment by woutergd** [comment]
Hi Groldan,

Not sure if it is useful for you, but I did some debugging tonight around this issue. I found out that the service bus works correctly and the binding with the catalog changes are also working. However, when you for instance update the contact info, it is not recognized as a change, delivering the following items in the log (in this case of the web-ui service):

```
2022-05-04 19:42:57.933 DEBUG 1 --- [nio-8080-exec-2] org.geoserver.cloud.bus.outgoing         : broadcasting RemoteGeoServerInfoModifyEvent(type: GeoServerInfo, id: geoserver, properties: updateSequence, event id: b55671bd-5edc-494e-b743-c5753a8c7c57, from: web-ui:172.29.0.9:8080, to: **, ts: 1651693377931) upon LocalConfigPostModifyEvent
2022-05-04 19:42:57.938 DEBUG 1 --- [nio-8080-exec-2] org.geoserver.cloud.bus.outgoing         : Not publishing remote event for no-op local change event LocalConfigPostModifyEvent(type: GeoServerInfo, id: null, diff: PropertyDiff(changes=[]), source: GeoServerImpl]
```

The message itself is generated on the following line: https://github.com/geoserver/geoserver-cloud/blob/4c248c26e3d38c7ec03141628278c966bb37f7d8/src/catalog-support/catalog-event-bus/src/main/java/org/geoserver/cloud/bus/GeoServerRemoteEventBroadcaster.java#L137.

If I look further into this, I think it is somehow related to the `Patch`-class, as the following condition needs to be validated before returning this message and avoiding the publishing on the message bus:

`if (patch.isPresent() && patch.get().isEmpty()) {`

I want to try to disable this check and run it again to see if that at least fixes the processing, but I have not yet the time to set up a complete development environment over here.

**Comment by groldan** [comment]
you nailed it, the problem goes deep into geoserver's ModificationProxy stuff, by the time the event is sent, the ModificationProxy has committed the changes to the referenced object (e.g. GeoServerInfo->ContactInfo) so the patch can't see the pre and after save object differs. All in all it's a known issue and I'll have to make amendments to correctly create the Patch.
Good digging!

**Comment by woutergd** [comment]
@groldan is there any update on this issue, or something I can help with to resolve this?

**Comment by groldan** [comment]
hi @woutergd, should be fixed in the latest main branch. Can you test 1.0-SNAPSHOT?

**Comment by woutergd** [comment]
@groldan I just updated, but found out afterwards that the docker images arent updated yet, seems something broken in your Github action? (https://github.com/geoserver/geoserver-cloud/runs/6861268911)

**Comment by woutergd** [comment]
@groldan I just noted that the issue should have been resolved when looking at this issue: https://github.com/actions/setup-node/issues/516

**Comment by woutergd** [comment]
@groldan it seems that now something else is blocking a successful build?

**Comment by woutergd** [comment]
@groldan thanks for checking out, the build was correct now. I deployed it in our lab environment, and it seems to work already better, but still not fully correct.

For instance when dropping and recreating a postgis-based layer, I receive the following error on the WMS-service:
`java.lang.reflect.UndeclaredThrowableExceptionCannot invoke "org.geoserver.catalog.Catalog.getResourcePool()" because "this.catalog" is null
`

I also get some issues on the WFS, but still need to dive further into the issue that occurs on that service.

**Comment by groldan** [comment]
Got it, forgot to bind the remote events resource pool processor during the refactoring. Working on it.

**Comment by groldan** [comment]
@woutergd should be fixed as of #241

**Comment by woutergd** [comment]
@groldan unfortunately it is not resolved. I get the following error log on the WMS service, the error is still the same that I got in the browser:

```
java.lang.reflect.UndeclaredThrowableException: null
        at jdk.proxy2/jdk.proxy2.$Proxy204.getStyle(Unknown Source) ~[na:na]
        at org.geoserver.wms.map.GetMapKvpRequestReader.getDefaultStyle(GetMapKvpRequestReader.java:949) ~[gs-wms-2.21-CLOUD.jar:2.21-CLOUD]
        at org.geoserver.wms.map.GetMapKvpRequestReader.processLayersStyles(GetMapKvpRequestReader.java:571) ~[gs-wms-2.21-CLOUD.jar:2.21-CLOUD]
        at org.geoserver.wms.map.GetMapKvpRequestReader.read(GetMapKvpRequestReader.java:400) ~[gs-wms-2.21-CLOUD.jar:2.21-CLOUD]
        at org.geoserver.wms.map.GetMapKvpRequestReader.read(GetMapKvpRequestReader.java:100) ~[gs-wms-2.21-CLOUD.jar:2.21-CLOUD]
        at org.geoserver.ows.Dispatcher.parseRequestKVP(Dispatcher.java:1511) ~[gs-ows-2.21-CLOUD.jar:2.21-CLOUD]
        at org.geoserver.ows.Dispatcher.dispatch(Dispatcher.java:684) ~[gs-ows-2.21-CLOUD.jar:2.21-CLOUD]
        at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:261) ~[gs-ows-2.21-CLOUD.jar:2.21-CLOUD]
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) ~[spring-webmvc-5.3.18.jar:5.3.18]
        at org.geoserver.cloud.wms.controller.WMSController.handleVirtualService(WMSController.java:90) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.18.jar:5.3.18]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.18.jar:5.3.18]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spr                                                                                                                                                                 ing-webmvc-5.3.18.jar:5.3.18]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[s                                                                                                                                                                 pring-webmvc-5.3.18.jar:5.3.18]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring                                                                                                                                                                 -webmvc-5.3.18.jar:5.3.18]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.18.jar:5                                                                                                                                                                 .3.18]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.18.jar:5.3.18]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.18.jar:5.3.18]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.18.jar:5.3.18]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.18.jar:5.3.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) ~[tomcat-embed-core-9.0.60.jar:4.0.FR]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.18.jar:5.3.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.60.jar:4.0.FR]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) ~[spring-security-web-5.6.2.jar:5.6.2]
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71) ~[gs-main-2.21-CLOUD.jar:2.21                                                                                                                                                                 -CLOUD]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) ~[spring-security-web-5.6.                                                                                                                                                                 2.jar:5.6.2]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) ~[spring-security-web-5.6                                                                                                                                                                 .2.jar:5.6.2]
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75) ~[gs-main-2.21-CLOUD.jar:2.21                                                                                                                                                                 -CLOUD]
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar:5.6.2]
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71) ~[gs-main-2.21-CLOUD.jar:2.21                                                                                                                                                                 -CLOUD]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122) ~[spring-security-web-5.6.2.jar:                                                                                                                                                                 5.6.2]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116) ~[spring-security-web-5.6.2.jar:                                                                                                                                                                 5.6.2]
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75) ~[gs-main-2.21-CLOUD.jar:2.21                                                                                                                                                                 -CLOUD]
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar:5.6.2]
        at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:53) ~[gs-main-2.21-CLOU                                                                                                                                                                 D.jar:2.21-CLOUD]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar:5.6.2]
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71) ~[gs-main-2.21-CLOUD.jar:2.21                                                                                                                                                                 -CLOUD]
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:150) ~[spring-secur                                                                                                                                                                 ity-web-5.6.2.jar:5.6.2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75) ~[gs-main-2.21-CLOUD.jar:2.21                                                                                                                                                                 -CLOUD]
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD]
        at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:81) ~[gs-main-2.21-CLOUD.jar:2.                                                                                                                                                                 21-CLOUD]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar:5.6.2]
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71) ~[gs-main-2.21-CLOUD.jar:2.21                                                                                                                                                                 -CLOUD]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) ~[spring-security-w                                                                                                                                                                 eb-5.6.2.jar:5.6.2]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) ~[spring-security-we                                                                                                                                                                 b-5.6.2.jar:5.6.2]
        at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:52) ~[gs-main-2                                                                                                                                                                 .21-CLOUD.jar:2.21-CLOUD]
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75) ~[gs-main-2.21-CLOUD.jar:2.21                                                                                                                                                                 -CLOUD]
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar:5.6.2]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) ~[spring-security-web-5.6.2.jar:5.6.2]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) ~[spring-security-web-5.6.2.jar:5.6.2]
        at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD                                                                                                                                                                 ]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:39) ~[gs-platform-2.21-CLOUD.jar:2.21-CLOUD]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:73) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD]
        at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:43) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.18.jar:5.3.18]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.18.jar:5.3.18]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.6                                                                                                                                                                 .6.jar:2.6.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.18.jar:5.3.18]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:156) ~[spring-web-5.3.18.jar:5.3.18]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.geoserver.catalog.impl.LocalWorkspaceCatalog$NameDequalifyingProxy.invoke(LocalWorkspaceCatalog.java:486) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD                                                                                                                                                                 ]
        ... 115 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "org.geoserver.catalog.Catalog.getResourcePool()" because "this.catalog" is null
        at org.geoserver.catalog.impl.StyleInfoImpl.getStyle(StyleInfoImpl.java:131) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.geoserver.catalog.impl.ModificationProxy.invoke(ModificationProxy.java:144) ~[gs-main-2.21-CLOUD.jar:2.21-CLOUD]
        at jdk.proxy2/jdk.proxy2.$Proxy132.getStyle(Unknown Source) ~[na:na]
        ... 120 common frames omitted

```

**Comment by groldan** [comment]
@woutergd ok, now it should be fixed as of #246

**Comment by woutergd** [comment]
@groldan the catalog issue is indeed resolved, thanks! I continue verifying the refresh, with the RC22 we had some issues but the latest snapshot seems te work fine as far as we can see now, we will continue testing it to see if any issues shows up.
